### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by xyf159** [charlesCXK/TorchSemiSeg#4]
I run the script.sh file and report an error.

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    from apex.parallel import DistributedDataParallel, SyncBatchNorm
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/optimizers/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/optimizers/fp16_optimizer.py", line 8, in <module>
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/dj/anaconda3/envs/py3.6torch1.6/bin/python: undefined symbol: THCudaHalfTensor_normall
Traceback (most recent call last):
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/dj/anaconda3/envs/py3.6torch1.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dj/anaconda3/envs/py3.6torch1.6/bin/python', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

My operating environment is pytorch1.6 CUDA10.0 gcc and g++ 7.5.0 ，Two 2080ti GPU。
I did not follow the method you said when installing apex,I keep failing to install according to that command，But I installed successfully through python3 setup.py install，So I turn to you for help。

**Comment by charlesCXK** [comment]
Hi, you need to install with "--cuda_ext --cpp_ext", or SyncBN will not work normally. 
I recommend you configure the environment with the semiseg.yaml.

**Comment by xyf159** [comment]
Thank you, I will try。
